services:
  alist:
    image: 'xhofe/alist:{{ ALIST_TAG }}'
    volumes:
      - '{{ mkdir(APP_DATA_PATH/"config") | chown }}:/opt/alist/data'
      - '{{ ALIST_DATA_PATH | mkdir | chown }}:/data'
#   {% if ALIST_EXPOSE_PORT > 0 %}
    ports:
      - '{{ ALIST_EXPOSE_PORT }}:5244'
#   {% endif %}
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - ALIST_ADMIN_PASSWORD={{ ALIST_ADMIN_PASSWORD }}
    networks:
      - nginx

networks:
  nginx:
    name: nginx
